# Generated by Django 5.0.14 on 2026-09-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Lote', 'Lote'), ('Comercial', 'Comercial')], max_length=30)),
                ('operation', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], default='Venta', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('parking', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(default=0, help_text='Área en m²')),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='inmobiliaria.property')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_user_property_favorite'),
        ),
    ]
